export const LOAD_CLOTHES = 'LOAD_CLOTHES';

export const FETCH_CLOTHES_COMPLETED = 'FETCH_CLOTHES_COMPLETED';
export const DELETE_CLOTHES_COMPLETED = 'DELETE_CLOTHES_COMPLETED';
export const ADD_CLOTHES_COMPLETED = 'ADD_CLOTHES_COMPLETED';
